### ISSUE TITLE
Chipotle sponsor icon might be too small

### ISSUE THREAD

**Issue by LTSENG01** [1757WestwoodRobotics/1757westwoodrobotics.github.io#43]

**Comment by 21kwebber** [comment]
I'll look into it soon.

**Comment by 21kwebber** [comment]
@LTSENG01 I'm not sure what you mean by "too small", the Chipotle logo is 1500x465. Would you prefer if I found a square logo?

**Comment by LTSENG01** [comment]
@21kwebber Sorry, I meant the displayed size of the logo (and other bronze sponsors) in main.scss.
