### ISSUE TITLE
Update crowdfunding button at bottom of site

### ISSUE THREAD

**Issue by LTSENG01** [1757WestwoodRobotics/1757westwoodrobotics.github.io#47]

**Comment by billyGirard** [comment]
Do you recommend we use the current button with a link to the page, or the official YouCaring widget?

**Comment by 21kwebber** [comment]
@billyGirard Most likely the current button, as that is the one we were using before.

**Comment by LTSENG01** [comment]
@billyGirard Don’t mind as long as it looks good. Current button for now is easier.
