### ISSUE TITLE
Update the footer crowdfunding banner

### ISSUE THREAD

**Issue by LTSENG01** [1757WestwoodRobotics/1757westwoodrobotics.github.io#78]
Our YouCaring crowdfunding thing doesn't exist anymore.

- Change the URL of the button to the sponsorship packet (https://github.com/1757WestwoodRobotics/1757westwoodrobotics.github.io/blob/master/community/sponsors/Westwood%20Robotics%20Sponsorship%20Information%202017-18.pdf)
- Change the wording of the text above the button to reflect "sponsor us"

**Comment by Bparazin** [comment]
The sponsorship packet is from last year. I assume the info is the same, but we should update that at some point

**Comment by LTSENG01** [comment]
@Bparazin Yep - we plan on doing that soon once we review the budget and stuff.
